### PR TITLE
Added: refresh() function now accepts optional 'data' parameter which ca...

### PR DESCRIPTION
**Pull request by BlackMan82**
Added: refresh() function now accepts optional 'data' parameter which can affect the way the items are scrolled in the view.

I added a functionality that I needed for my project. If you find it usefull also for you or the others, merge it into.

The functionality enhances the current behaviour. The user can trigger the 'vsRepeatTrigger' with additional data - an object with the following properties:
* startIndex - index of the item that should be considered as the first item; it is not necessarily the one that will be rendered at the first position, the first rendered item depends also on the startIndexPosition;
* startIndexPosition 
  * position of the first item, i.e. how much it should be scrolled; if not provided, no scrolling is performed;
  * either a number of pixels or one of the following strings: 'top', 'middle', 'bottom', 'inview' is the same as 'inview#top', 'inview#middle', 'inview#bottom', 'inview#auto';
  * the 'inview#\<position\>' settings means that if the item is already in the view, nothing is scrolled, but if it is not, then the item will be scrolled accordingly (to be in the \<position\>); 
  * position 'auto' means that it will be either 'top' or 'bottom' depending on what is closer to the current item position;

### CODE REVIEW

**Comment by kamilkp** [comment]
Nice job. If i remember correclty, there were several people requesting a functionality like that. I saw some (commented out), can you remove them, and also copy the description of how your functionality works and paste it into the readme.md? i'll definitely merge it then, thanks.

**Comment by BlackMan82** [comment]
OK, I'll improve the readme and cleanup the code. I was also thinking about integrating the idea of #8, i.e. that the `startIndex` and `startIndexPosition` could be also binded to directive's attributes. A user would then have two possibilities to affect the behaviour.

**Comment by BlackMan82** [comment]
Well, it took some time since I was busy but I updated the readme and I also incorporated a mechanism similar to the #8, i.e. the scrolling can be controlled also via directive attributes.

I just renamed the settings: `startIndex` -> `scrollIndex`, `startIndexPosition` -> `scrollIndexPosition`.

**Comment by kamilkp** [comment]
Great. One more thing. Could you not wrap my one-statement `if`s with curly braces, change double quotes to single quotes and all that? I'd like to have changes that only affect the functionality that you implemented

**Comment by BlackMan82** [comment]
Done ;)

**Comment by kamilkp** [comment]
There is is a bug #43 with the merged functionality. Is that an easy fix?

**Comment by BlackMan82** [comment]
Fixed in #44.

**Pull request merged**
