### PR TITLE
#73 Heavy garbagecollection during refresh()

### PR DESCRIPTION
**Pull request by hhravn**
Reuse scope for entire map operation, to avoid heavy(!) garbagecollection.

### CODE REVIEW

**Comment by janhartigan** [comment]
What sort of performance benefits have you seen out of this?

**Comment by hhravn** [comment]
@janhartigan In our use case (more than 250k rows, frequent refreshes) garbage collection went from 50+MB for a refresh to about nothing, according to the sparse documentation from back then. If you have problems with refresh performance i would look into this, try it out. I have since moved to a new project, and the project has moved to a different solution, so i have no hard evidence on hand. Sorry :o)

**Comment by janhartigan** [comment]
@hhravn ah ok, thanks for the info.

**Comment by kamilkp** [comment]
v2.x doesn't use this ad-hoc scope at all.

**Pull request closed without merging**
