### PR TITLE
#129 #116 Move to last item if model shrinks

### PR DESCRIPTION
**Pull request by CalMlynarczyk**
If the collection shrinks while we are scrolled below its new rendered size,
the scroll position currently doesn't change. This commit moves us to the
end of the collection if this scenario occurs.

### CODE REVIEW

**Comment by aspickard** [comment]
This fixed an issue that I'm having - any reason this hasn't been accepted?

**Comment by alevinru** [comment]
Please merge this

**Comment by Koc** [comment]
ping @kamilkp

**Comment by Shemesh** [comment]
hi @kamilkp 
please merge this

**Comment by CyborgMaster** [comment]
This fixes #129, which I need in my project.  Let us know what we can do to help it get merged.  I'm using @CalMlynarczyk's fork for now.

**Comment by kwypchlo** [comment]
@kamilkp please merge this PR. This is super useful fix and I've confirmed it working on my project too (like the rest of the guys here) 👍

**Comment by codyhazelwood** [comment]
I am also using this in a project and can confirm it works.  +1 for a merge @kamilkp - or maybe add someone else as a maintainer who can merge it?

**Comment by kwypchlo** [comment]
@CalMlynarczyk could you also run `grunt uglify` and commit the min version? If we want to merge it eventually, we should have the minified version updated too.

**Comment by kamilkp** [comment]
I will take a look at this in the evening and merge it most likely.

Kamil Pękala

Dnia 02.08.2017 o godz. 15:42 Karol Wypchło <notifications@github.com> napisał(a):

**Comment by CalMlynarczyk** [comment]
Rebased on the latest changes and added the regenerated minified version.

**Comment by kwypchlo** [comment]
@kamilkp can you also publish 1.1.8 form current master ?

**Pull request merged**
